@startuml

package Canvas {
    [GradebookPage]
    [CalendarPage]
}

package Browser {
    component DOM {
        portin readHTML
        portin addListener
        portin updateCSS
    }

    portout URL
}

package Extension {
    [GradebookFeature]
    [GamificationFeature]
    [Manifest]
}

URL ---> Manifest
Manifest ---> GradebookFeature
Manifest ---> GamificationFeature

GradebookFeature ---> readHTML
GradebookFeature ---> addListener
GradebookFeature ---> updateCSS

GamificationFeature ---> readHTML
GamificationFeature ---> addListener
GamificationFeature ---> updateCSS

DOM ---> GradebookPage
DOM ---> CalendarPage

@enduml